version: "3.8"
services:
  airflow:
    build:
      context: ./
      dockerfile: Dockerfile.airflow
    image: airflowimage
    container_name: customer-segmentation-airflow
    ports:
      - "8080:8080"
    
  streamlitapp:
    build:
      context: ./
      dockerfile: Dockerfile.streamlit
    image: streamlitimage
    container_name: customer-segmentation-streamlit
    ports:
      - "8501:8501"
