stages:
  training:
    cmd: python src/ModelTesting/training.py
    deps:
      - src/components/data_ingestion.py
      - src/components/data_transformation.py
      - src/components/model_trainer.py
    outs:
      - artifacts/marketing_campaign.csv
      - artifacts/marketing_cleaned.csv
      - artifacts/marketing_encoded.csv
      - artifacts/marketing_clustered.csv